// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	PLATFORM_COMMISSION_DEFAULT: "0.15";
	CANCELLATION_PENALTY_DEFAULT: "0.20";
	MEDIA_BUCKET: R2Bucket;
	DB: D1Database;
}
